# Generated by Django 5.0.2 on 2025-03-02 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelingdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Pig ID')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('weight', models.IntegerField(verbose_name='Weight (kg)')),
                ('status', models.CharField(max_length=100, verbose_name='Health status')),
                ('arrival', models.DateField(verbose_name='arrival date')),
                ('location', models.CharField(max_length=255, verbose_name='address of seller farm')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='modelingdata.breeds')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sex', to='modelingdata.sex')),
                ('tag_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagcolour', to='modelingdata.tagscolour')),
            ],
            options={
                'verbose_name_plural': 'Invens',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.CreateModel(
            name='Farrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('number_born', models.IntegerField(verbose_name='No. Born')),
                ('mortality', models.IntegerField(verbose_name='Mortality')),
                ('boar_id', models.ForeignKey(limit_choices_to={'sex__name': 'BOAR'}, on_delete=django.db.models.deletion.CASCADE, related_name='fallowing_as_boar', to='inven.inven', verbose_name='Boar')),
                ('sow_id', models.ForeignKey(limit_choices_to={'sex__name': 'SOW'}, on_delete=django.db.models.deletion.CASCADE, related_name='farrowing_as_soW', to='inven.inven', verbose_name='Sow')),
            ],
            options={
                'verbose_name': 'Farrowing',
                'verbose_name_plural': 'Farrowings',
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Litter ID')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelingdata.sex', verbose_name='Sex')),
            ],
            options={
                'verbose_name': 'Litter',
                'verbose_name_plural': 'Litters',
            },
        ),
        migrations.CreateModel(
            name='Litter_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inven.farrowing', verbose_name='Farrowing')),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inven.litter', verbose_name='Litter')),
            ],
            options={
                'verbose_name': 'Litter_allocation',
                'verbose_name_plural': 'Litter_allocations',
            },
        ),
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Mating Date')),
                ('boar_id', models.ForeignKey(limit_choices_to={'sex__name': 'BOAR'}, on_delete=django.db.models.deletion.CASCADE, related_name='matings_as_boar', to='inven.inven', verbose_name='Boar')),
                ('sow_id', models.ForeignKey(limit_choices_to={'sex__name': 'SOW'}, on_delete=django.db.models.deletion.CASCADE, related_name='matings_as_sow', to='inven.inven', verbose_name='Sow')),
            ],
        ),
        migrations.CreateModel(
            name='testP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('health', models.CharField(max_length=100, verbose_name='Health')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inven.mating', verbose_name='Mating Date')),
            ],
        ),
        migrations.CreateModel(
            name='Weaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_wean', models.DateField(verbose_name='weaning date')),
                ('no_wean', models.IntegerField(verbose_name='number Wean')),
                ('avg_weight', models.IntegerField(verbose_name='Average Weight')),
                ('mortality', models.IntegerField(verbose_name='mortality after farrowing')),
                ('birth_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inven.farrowing', verbose_name='Date farrowed')),
            ],
            options={
                'verbose_name': 'Weaning',
                'verbose_name_plural': 'Weanings',
            },
        ),
    ]
